exporter_name: products_csv
exporter_type: csv
collection: products
no_headers: false
offset: 0
order: desc
fields:
 - header: "gid"
   path: "_gid"
 - header: "created at"
   path: "_created_at"
 - header: "categories"
   path: "categories"
 - header: "current price"
   path: "current_price"
