exporter_name: products_csv
exporter_type: csv
collection: products
no_headers: false
offset: 0
order: desc
fields:
 - header: "gid"
   path: "_gid"
 - header: "created at"
   path: "_created_at"
 - header: "title"
   path: "title"
 - header: "walmart number"
   path: "walmart_number"
 - header: "categories"
   path: "categories"
 - header: "current price"
   path: "current_price"
 - header: "original price"
   path: "original_price"
 - header: "publisher"
   path: "publisher"
 - header: "rating"
   path: "rating"
 - header: "reviews count"
   path: "reviews_count"
